spring:
  application:
    name: test_transactional
  datasource:
    url: jdbc:mysql://47.109.152.66:3306/study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml


thread-pool-param:
  corePoolSize: 4
  maximumPoolSize: 10
  keepAliveTime: 60
  unit: SECONDS # NANOSECONDS、MICROSECONDS、MILLISECONDS、SECONDS、MINUTES、HOURS、DAYS
